FROM ghcr.io/tauffer-consulting/domino-base-piece:latest
# Install specific requirements to run OpenCV
RUN apt-get update

# Need to copy pieces source code
COPY config.toml domino/pieces_repository/
COPY pieces domino/pieces_repository/pieces
COPY .domino domino/pieces_repository/.domino
